### ISSUE TITLE
Cannot create tunnel

### ISSUE THREAD

**Issue by Satont** [ngrok/ngrok-go#147] opened 2023-12-21 09:14 UTC
```go
tun, err := ngrok.Listen(
  ngrokCtx,
  ngrok_config.HTTPEndpoint(),
)
```

Cannot open tunnel due some ngrok api outage, this code never resolves.

**Comment by bobzilladev** [comment] 2023-12-22 16:09
Hello, thanks for your feedback! To debug this case it would be helpful to add a logger as in the example below.

Since the code snippet doesn't contain any information about an Authtoken, I would guess the issue is that an Authtoken is not set. This can be solved by signing up for a free ngrok account, and then setting the Authtoken using `ngrok.WithAuthtokenFromEnv()` or `ngrok.WithAuthtoken("<AUTH_TOKEN>")`.

```go
package main

import (
  "context"
  "fmt"
  "log"
  "net/http"
  "time"

  "golang.ngrok.com/ngrok"
  ngrok_config "golang.ngrok.com/ngrok/config"
  ngrok_log "golang.ngrok.com/ngrok/log"
)

func main() {
  if err := run(context.Background()); err != nil {
    log.Fatal(err)
  }
}

// Simple logger that forwards to the Go standard logger.
type logger struct {
  lvl ngrok_log.LogLevel
}

func (l *logger) Log(ctx context.Context, lvl ngrok_log.LogLevel, msg string, data map[string]interface{}) {
  if lvl > l.lvl {
    return
  }
  lvlName, _ := ngrok_log.StringFromLogLevel(lvl)
  log.Printf("[%s] %s %v", lvlName, msg, data)
}

func run(ngrokCtx context.Context) error {
  lvl, err := ngrok_log.LogLevelFromString("debug")
  if err != nil {
    return err
  }
  secureConnection, err := ngrok.Listen(
    ngrokCtx,
    ngrok_config.HTTPEndpoint(),
    // ngrok.WithAuthtokenFromEnv(), // set from the NGROK_AUTHTOKEN environment variable
    // ngrok.WithAuthtoken("<AUTH_TOKEN>"), // set authtoken directly
    ngrok.WithLogger(&logger{lvl}),
  )
  if err != nil {
    return err
  }

  log.Println("secure connection created:", secureConnection.URL())

  return http.Serve(secureConnection, http.HandlerFunc(handler))
}

func handler(w http.ResponseWriter, r *http.Request) {
  fmt.Fprintln(w, "Hello from ngrok-go!\n\nThe time is now: ", time.Now().String())
}
```

This outputs:
```
[error] failed to reconnect session map[err:authentication failed: Usage of ngrok requires a verified account and authtoken.

Sign up for an account: https://dashboard.ngrok.com/signup
Install your authtoken: https://dashboard.ngrok.com/get-started/your-authtoken

ERR_NGROK_4018
```

**Comment by bobzilladev** [comment] 2024-01-02 15:46
Going to close this out, feel free to reopen it if you have any more questions. Thanks for writing in!

**Closed by bobzilladev** 2024-01-02 15:46 UTC

**Comment by Satont** [comment] 2024-01-04 10:17
@bobzilladev thanks for the answer.
